# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  displayName: 'Run Pulumi test'
  inputs:
       azureSubscription: 'service'
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
         export PATH=$HOME/.pulumi/bin:$PATH
         helm version
         export AZURE_STORAGE_KEY=$(az storage account keys list -g pulumi-dev-shared -n pulumitesting --query [0].value -o json | tr -d '"')
         export AZURE_STORAGE_ACCOUNT=pulumitesting
         export AZURE_KEYVAULT_AUTH_VIA_CLI=true
         #export AZDO_ORG_SERVICE_URL=***org url***
         export AZDO_PERSONAL_ACCESS_TOKEN=$(System.AccessToken)
         pulumi login azblob://pulumitesting?storage_container=pulumitesting
         export AZURE_CLIENT_ID=$(AzureDevopsClientId)
         export ARM_CLIENT_ID=$(AzureDevopsClientId)
         export AZURE_CLIENT_SECRET =$(AzureDevopsClientSecret)
         export ARM_CLIENT_SECRET=$(AzureDevopsClientSecret)
         export AZURE_TENANT_ID =$(az account show --query tenantId -o json | tr -d '"')
         export ARM_TENANT_ID=$(az account show --query tenantId -o json | tr -d '"')
         export ARM_SUBSCRIPTION_ID=$(az account show --query id -o json | tr -d '"')
         pulumi preview

